version: '3.4'
networks:
  api:
    driver: "bridge"
services:
  fapp:
    image: ${DOCKER_REGISTRY-}fapp
    build:
      context: .
      dockerfile: FApp/Dockerfile
    depends_on:
      - postgredb
    networks:
      - api
  postgredb:
    image: postgres
    container_name: postgredb
    ports:
    - 5432:5432
    environment:
       POSTGRES_DB: docker
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
    networks:
      - api